# Loads default set of integrations. Do not remove.
default_config:

homeassistant: !include homeassistant.yaml

logger:
  default: info
  logs:
    homeassistant.helpers.template: error


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
#lovelace:
#  mode: yaml

# Text to speech
tts:
  - platform: google_translate

recorder: !include recorder.yaml
    
automation: !include automations.yaml
automation mine: !include_dir_merge_list automation/
template: !include_dir_merge_list template/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/

script: !include scripts.yaml
scene: !include scenes.yaml

input_number: !include_dir_named input_number/
input_boolean: !include_dir_named input_boolean/
input_select: !include_dir_named input_select/
input_datetime: !include_dir_named input_datetime/
input_text: !include_dir_named input_text/
timer: !include_dir_named timers/
utility_meter: !include utility_meter.yaml
http: !include http.yaml
